Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-11, with the labels that each got.

#317 [Fix/315] 보안 관련 비밀번호, 다른회원 프로필 조회 수정
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/PasswordService.java
  src/main/java/com/gamegoo/util/CodeGeneratorUtil.java
Labels: :bug: bug

#318 🐛[Fix] refresh Token 발급 시 회원 정보 수정 날짜 업데이트 되는거 수정
  src/main/generated/com/gamegoo/domain/member/QMember.java
  src/main/generated/com/gamegoo/domain/member/QRefreshToken.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/domain/member/RefreshToken.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/repository/member/RefreshTokenRepository.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :sparkles: feature, :bug: bug

#322 [Test/321] ChatServiceTest 로직 수정 및 테스트 자동 실행 설정
  .github/workflows/pr-test.yml
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/test/java/com/gamegoo/integration/chat/ChatServiceTest.java
Labels: :bug: bug, ✅ test

#323 🐛[Fix] 비밀번호 재설정을 위한 인증코드 발송 및 검증, 새로운 비밀번호로 수정
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/PasswordService.java
Labels: :bug: bug
