Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-03, with the labels that each got.

#2 [Docs/1] Swagger 설정
  build.gradle
  src/main/java/com/gamegoo/config/SwaggerConfig.java
  src/main/java/com/gamegoo/controller/TestController.java
Labels: :memo: documentation

#4 [Feat/3] API 응답 통일, 공통 에러 설정
  build.gradle
  src/main/java/com/gamegoo/apiPayload/ApiResponse.java
  src/main/java/com/gamegoo/apiPayload/code/BaseCode.java
  src/main/java/com/gamegoo/apiPayload/code/BaseErrorCode.java
  src/main/java/com/gamegoo/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/gamegoo/apiPayload/code/ReasonDTO.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/gamegoo/apiPayload/exception/GeneralException.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/TempHandler.java
  src/main/java/com/gamegoo/controller/TestController.java
Labels: :sparkles: feature

#11 [cicd/6] Docker 배포
  .gitignore
  Dockerfile
Labels: :construction_worker: ci

#12 👷[Ci]:Docker 배포 관련
  build.gradle
Labels: :construction_worker: ci

#14 [Feat/13] application.yml 설정 추가
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: feature

#15 [Cicd/9] CI Github Action 활용해서 docker hub에 자동으로 push하기
  .github/workflows/gradle.yml
  build.gradle
Labels: :construction_worker: ci
