Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-10, with the labels that each got.

#253 [Feat/247] 매너 평가 도메인 회원 탈퇴 관련 로직 추가
  src/main/java/com/gamegoo/repository/manner/MannerRatingRepository.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/service/notification/NotificationService.java
Labels: :sparkles: feature, :recycle: refactor

#255 [Refactor/254] 게시판 글 목록 조회 API 응답에 totalPage, totalCount 추가
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor

#260 [Fix/259] 게시판 필터링 조회 오류
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#261 :bug: [Fix/258] GameStyleIdList가 Empty일 때 예외처리
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/converter/MatchingConverter.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :bug: bug

#264 :bug: [fix/263] matchAPI 디버깅용 코드 추가
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
Labels: :bug: bug

#267 [Refactor/266] 다른 회원 프로필 조회 API 응답에 매너 평가를 한 사람의 수 추가
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/repository/manner/MannerRatingRepository.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :recycle: refactor

#269 Fix/263
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :bug: bug

#270 [Refactor/268] 모든 API 요청에 대한 로그 출력 및 기존 로그 코드 수정
  build.gradle
  src/main/java/com/gamegoo/aop/LogAspect.java
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :recycle: refactor

#271 [Refactor/268] api 요청 로그 format 수정
  src/main/java/com/gamegoo/aop/LogAspect.java
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/domain/gamestyle/GameStyle.java
  src/main/java/com/gamegoo/domain/gamestyle/MemberGameStyle.java
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#272 [Fix/262] Auth & Profile 관련 에러 수정
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/domain/common/BaseDateTimeEntity.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :bug: bug

#274 [Fix/273] 언랭크 사용자 처리
  src/main/java/com/gamegoo/domain/member/Tier.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :bug: bug

#278 [Fix/277] 알림 유형별 타입 값 추가
  src/main/java/com/gamegoo/converter/NotificationConverter.java
Labels: :bug: bug

#280 [Feat/279] 3000 서버용 internal API 구현
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/InternalController.java
Labels: :sparkles: feature

#283 [Fix/281] 게시판 글 작성,수정 시 게임모드 칼바람일때 포지션 null 값 허용
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#285 [Refactor/284] 매너/비매너 평가 조회 API 응답에 mannerId 추가
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :recycle: refactor

#287 [Fix/286] countUnreadChats 메소드의 lastViewDate 비교 쿼리 수정
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
Labels: :bug: bug

#290 [Feat/288] 매너평가 메시지에 timestamp 추가 및 스케줄러 실행 간격 변경
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
  src/main/java/com/gamegoo/service/socket/SocketService.java
Labels: :sparkles: feature

#291 [Fix/289] 매너평가 관련 알림 pageUrl 버그 수정
  src/main/java/com/gamegoo/converter/NotificationConverter.java
Labels: :bug: bug

#293 [Fix/273] 회원가입 예외처리 이상한거 해결
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :bug: bug

#295 [Feat/294] 프로필 조회에 wantP 추가하기
  src/main/generated/com/gamegoo/domain/member/QMember.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :bug: bug

#297 [Fix/296] 인증코드 메일 제목 및 매칭 SUCCESS internal API endpoint 수정
  src/main/java/com/gamegoo/controller/InternalController.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :bug: bug

#299 [Feat/298] riot 계정이 있을 경우 무조건 회원가입 가능하도록 수정
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :bug: bug

#305 [Fix/304] 회원용 게시판 글 조회 API - champion 정보 응답값 수정
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#308 [Refactor/307] 게시판 글 목록 조회 API 응답에 tag 추가
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor

#309 [Refactor/306] 매너평가 메시지 스케줄러 실행 주기 변경
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
Labels: :recycle: refactor

#311 [Refactor/310] 게시판 포지션 필터링 기준을 주포지션 기준으로 변경
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
Labels: :recycle: refactor

#312 [Feat/282] 매일 아침 7시 riot 정보 업데이트
  src/main/java/com/gamegoo/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/gamegoo/domain/champion/MemberChampion.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :bug: bug

#314 🐛[Fix] Riot 소환사 명 없을 경우 인증 안되도록 확인
  src/main/java/com/gamegoo/service/member/RiotService.java
Labels: :bug: bug
