Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-09, with the labels that each got.

#198 [Refactor/173] chatCommandService 메소드 테스트 코드 작성
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/test/java/com/gamegoo/integration/chat/ChatServiceTest.java
  src/test/java/com/gamegoo/integration/member/ProfileServiceTest.java
  src/test/java/com/gamegoo/member/ProfileServiceTest.java
Labels: ✅ test

#200 [Fix/199] 채팅 메소드 테스트 실패 케이스 수정
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
Labels: :bug: bug

#195 [Fix/194] 매칭 수정사항 변경 및 ErrorStatus 변경
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :bug: bug

#206 [Feat/202] 모든 친구 id 목록 조회 API 구현
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/service/member/FriendService.java
Labels: :sparkles: feature

#205 [Feat/201] 친구 검색 기능 구현 및 친구 목록 조회 페이징 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/dto/notification/NotificationResponse.java
  src/main/java/com/gamegoo/repository/friend/FriendRepository.java
  src/main/java/com/gamegoo/repository/friend/FriendRepositoryCustom.java
  src/main/java/com/gamegoo/repository/friend/FriendRepositoryCustomImpl.java
  src/main/java/com/gamegoo/repository/friend/FriendRequestsRepository.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/util/SortUtil.java
Labels: :sparkles: feature

#208 [Refactor/207] 채팅 API에 탈퇴 관련 로직 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :recycle: refactor

#210 [Feat/209] 채팅방 목록 조회 API 페이징 추가
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature

#212 [Refactor/211] 친구 목록 조회 API 응답에 탈퇴 관련 값 추가
  src/main/java/com/gamegoo/converter/MemberConverter.java
Labels: :recycle: refactor

#214 [Feat/213] 즐겨찾기 설정/해제 API 탈퇴여부 검증 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/service/member/FriendService.java
Labels: :sparkles: feature

#204 [Fix/203] 매칭 status 변경할 때 gameMode 변경
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/repository/matching/MatchingRecordRepository.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature, :bug: bug

#226 [Feat/225] 매너 레벨 상승/하락 시 알림 등록 기능 추가
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature

#222 [Fix/219] Champion Response 변경
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#223 [feat/220] 탈퇴한 사용자라는 error 보내기
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :sparkles: feature

#221 [Feat/218] 매칭 우선순위 세부 작업 진행
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/domain/matching/MatchingRecord.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature

#224 [Feat/217] 차단 목록 삭제 기능 구현
  src/main/generated/com/gamegoo/domain/QBlock.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/BlockController.java
  src/main/java/com/gamegoo/domain/Block.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/service/member/BlockService.java
Labels: :sparkles: feature

#228 [Refactor/227] 차단 도메인 회원 탈퇴 관련 로직 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/BlockService.java
Labels: :recycle: refactor

#230 [Feat/229] 매칭 성공 1시간 후 매너평가 시스템 메시지 전송 기능 구현
  src/main/generated/com/gamegoo/domain/matching/QMatchingRecord.java
  src/main/java/com/gamegoo/GamegooApplication.java
  src/main/java/com/gamegoo/domain/matching/MatchingRecord.java
  src/main/java/com/gamegoo/repository/matching/MatchingRecordRepository.java
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/socket/SocketService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#234 [Feat/231] 테스트 수정사항 반영
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :bug: bug

#233 [Feat/232] 회원 탈퇴 API에 채팅, 친구 관련 로직 추가
  src/main/java/com/gamegoo/repository/friend/FriendRequestsRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature

#237 [Feat/236] 게시판 도메인 회원 탈퇴 관련 로직 추가
  src/main/generated/com/gamegoo/domain/board/QBoard.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature

#241 [Refactor/239] 알림 목록 조회 API 응답 값 수정
  src/main/java/com/gamegoo/converter/NotificationConverter.java
Labels: :recycle: refactor

#240 [Refactor/238] 게시판 글 삭제 방식 변경
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor

#196 [Feat/178] 매너 레벨 조회 시 상위 n% 정보 추가 구현
  src/main/generated/com/gamegoo/domain/member/QMember.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :recycle: refactor, :bug: bug

#243 [Refactor/242] 채팅 시스템 메시지 응답 형태 변경 및 기타 버그 수정
  src/main/generated/com/gamegoo/domain/chat/QChat.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chat.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/scheduler/SchedulerService.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/resources/application.yml
Labels: :recycle: refactor, :bug: bug

#245 [Feat/244] 프론트 도메인 CORS 설정 추가
  src/main/java/com/gamegoo/config/SecurityConfig.java
Labels: :sparkles: feature

#248 [Fix/246] 매너/비매너 평가 수정 시 isExist 값 업데이트
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :bug: bug

#250 [Fix/249] 매너/비매너 평가 수정 시 모든 값이 상쇄될 경우의 로직 변경
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :bug: bug

#252 [Refactor/251] 내가 작성한 게시판 글 목록 조회 API 응답에 totalPage, totalCount 추가
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor
