Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-07, with the labels that each got.

#51 :sparkles: [Feat] 회원 API 전체 리팩토링 및 API 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/MemberController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/dto/member/EmailCodeRequestDTO.java
  src/main/java/com/gamegoo/dto/member/EmailDTO.java
  src/main/java/com/gamegoo/dto/member/EmailRequestDTO.java
  src/main/java/com/gamegoo/dto/member/GameStyleRequestDTO.java
  src/main/java/com/gamegoo/dto/member/JoinRequestDTO.java
  src/main/java/com/gamegoo/dto/member/LoginResponseDTO.java
  src/main/java/com/gamegoo/dto/member/PasswordRequestDTO.java
  src/main/java/com/gamegoo/dto/member/PositionRequestDTO.java
  src/main/java/com/gamegoo/dto/member/ProfileImageRequestDTO.java
  src/main/java/com/gamegoo/dto/member/RefreshTokenRequestDTO.java
  src/main/java/com/gamegoo/dto/member/RefreshTokenResponseDTO.java
  src/main/java/com/gamegoo/filter/JWTFilter.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/security/CustomUserDetailService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/service/member/RefreshTokenService.java
  src/main/java/com/gamegoo/util/JWTUtil.java
  src/main/java/com/gamegoo/util/SecurityUtil.java
Labels: :sparkles: feature, :recycle: refactor, :bug: bug

#53 [Feat/49] 차단한 회원 목록 조회 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/PageHandler.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/MemberController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/service/member/MemberService.java
Labels: :sparkles: feature

#55 [Feat/49] DTO 이름 및 변수명, ErrorStatus 수정
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/MemberController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/MemberService.java
Labels: :sparkles: feature

#56 [Feat/54] 차단 해제 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/MemberController.java
  src/main/java/com/gamegoo/domain/Block.java
  src/main/java/com/gamegoo/repository/member/BlockRepository.java
  src/main/java/com/gamegoo/service/member/MemberService.java
Labels: :sparkles: feature

#58 [Fix/57] 회원 차단 API uri 수정
  src/main/java/com/gamegoo/controller/member/MemberController.java
Labels: :bug: bug

#60 [Feat/48] 회원 신고 API 구현
  build.gradle
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/ReportHandler.java
  src/main/java/com/gamegoo/controller/report/ReportController.java
  src/main/java/com/gamegoo/domain/report/Report.java
  src/main/java/com/gamegoo/domain/report/ReportType.java
  src/main/java/com/gamegoo/domain/report/ReportTypeMapping.java
  src/main/java/com/gamegoo/dto/report/ReportRequest.java
  src/main/java/com/gamegoo/dto/report/ReportResponse.java
  src/main/java/com/gamegoo/repository/report/ReportRepository.java
  src/main/java/com/gamegoo/repository/report/ReportTypeMappingRepository.java
  src/main/java/com/gamegoo/repository/report/ReportTypeRepository.java
  src/main/java/com/gamegoo/service/report/ReportService.java
Labels: :sparkles: feature

#62 [Feat/48] 회원 신고 API 수정.
  src/main/java/com/gamegoo/controller/report/ReportController.java
  src/main/java/com/gamegoo/dto/report/ReportRequest.java
  src/main/java/com/gamegoo/dto/report/ReportResponse.java
  src/main/java/com/gamegoo/repository/report/ReportTypeRepository.java
  src/main/java/com/gamegoo/scripts/ReportTypeInitializer.java
  src/main/java/com/gamegoo/service/report/ReportService.java
Labels: :sparkles: feature, :recycle: refactor, :memo: documentation

#65 [Feat/41] Riot API 개발
  .github/workflows/gradle.yml
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/config/AppConfig.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/controller/member/RiotController.java
  src/main/java/com/gamegoo/domain/Member.java
  src/main/java/com/gamegoo/domain/champion/Champion.java
  src/main/java/com/gamegoo/domain/champion/MemberChampion.java
  src/main/java/com/gamegoo/domain/gamestyle/MemberGameStyle.java
  src/main/java/com/gamegoo/dto/member/EmailCodeRequestDTO.java
  src/main/java/com/gamegoo/dto/member/EmailRequestDTO.java
  src/main/java/com/gamegoo/dto/member/GameStyleRequestDTO.java
  src/main/java/com/gamegoo/dto/member/JoinRequestDTO.java
  src/main/java/com/gamegoo/dto/member/LoginResponseDTO.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/dto/member/PasswordRequestDTO.java
  src/main/java/com/gamegoo/dto/member/PositionRequestDTO.java
  src/main/java/com/gamegoo/dto/member/ProfileImageRequestDTO.java
  src/main/java/com/gamegoo/dto/member/RefreshTokenRequestDTO.java
  src/main/java/com/gamegoo/dto/member/RefreshTokenResponseDTO.java
  src/main/java/com/gamegoo/dto/member/RiotResponse.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/repository/member/ChampionRepository.java
  src/main/java/com/gamegoo/repository/member/GameStyleRepository.java
  src/main/java/com/gamegoo/repository/member/MemberChampionRepository.java
  src/main/java/com/gamegoo/repository/member/MemberGameStyleRepository.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/scripts/ChampionInitializer.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/service/member/RiotService.java
  src/main/resources/application.yml
  src/main/resources/static/champion.json
  src/main/resources/test.json
Labels: :sparkles: feature, :recycle: refactor, :construction_worker: ci, :bug: bug

#63 [Feat/52] 게시판 글 작성 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/BoardHandler.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/domain/Member.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/domain/board/BoardGameStyle.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardGameStyleRepository.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/scripts/GameStyleInitializer.java
  src/main/java/com/gamegoo/scripts/ReportTypeInitializer.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature, :recycle: refactor, :bug: bug

#71 [Fix/70] 배포 환경 403 에러 및 API 버그 수정
  .github/workflows/gradle.yml
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/TestController.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :construction_worker: ci, :bug: bug

#73 :sparkles: [Feat] api url /v1/으로 변경 및 cors 설정 추가
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/MemberController.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/controller/member/RiotController.java
  src/main/java/com/gamegoo/controller/report/ReportController.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
Labels: :sparkles: feature

#75 Feat/41
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/repository/member/EmailVerifyRecordRepository.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/service/member/RiotService.java
Labels: :bug: bug

#77 [Feat/76] 채팅방 uuid 목록 조회 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/ChatHandler.java
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/Member.java
  src/main/java/com/gamegoo/domain/chat/Chatroom.java
  src/main/java/com/gamegoo/domain/chat/MemberChatroom.java
  src/main/java/com/gamegoo/domain/enums/ChatroomStatus.java
  src/main/java/com/gamegoo/dto/chat/ChatRequest.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/ChatroomRepository.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature

#67 [Feat/61] 게시판 글 수정, 삭제 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/domain/board/BoardGameStyle.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature

#80 [Feat/61] 게시판 글 수정, 삭제 API 구현
  src/main/java/com/gamegoo/controller/board/BoardController.java
Labels: :bug: bug

#78 [Feat/64] 게시판 글 목록 조회 API 구현
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature, :memo: documentation, :bug: bug

#82 Fix/74 GameStyle 에러 해결 및 JWT 예외처리 추가
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/util/JWTUtil.java
Labels: :recycle: refactor, :bug: bug

#89 [Feat/86] 채팅방 목록 조회 API 구현
  build.gradle
  src/main/generated/com/gamegoo/domain/QBlock.java
  src/main/generated/com/gamegoo/domain/QEmailVerifyRecord.java
  src/main/generated/com/gamegoo/domain/QFriend.java
  src/main/generated/com/gamegoo/domain/QFriendRequests.java
  src/main/generated/com/gamegoo/domain/QMatchingRecord.java
  src/main/generated/com/gamegoo/domain/QMember.java
  src/main/generated/com/gamegoo/domain/board/QBoard.java
  src/main/generated/com/gamegoo/domain/board/QBoardGameStyle.java
  src/main/generated/com/gamegoo/domain/champion/QChampion.java
  src/main/generated/com/gamegoo/domain/champion/QMemberChampion.java
  src/main/generated/com/gamegoo/domain/chat/QChat.java
  src/main/generated/com/gamegoo/domain/chat/QChatroom.java
  src/main/generated/com/gamegoo/domain/chat/QMemberChatroom.java
  src/main/generated/com/gamegoo/domain/common/QBaseDateTimeEntity.java
  src/main/generated/com/gamegoo/domain/gamestyle/QGameStyle.java
  src/main/generated/com/gamegoo/domain/gamestyle/QMemberGameStyle.java
  src/main/generated/com/gamegoo/domain/manner/QMannerKeyword.java
  src/main/generated/com/gamegoo/domain/manner/QMannerRating.java
  src/main/generated/com/gamegoo/domain/manner/QMannerRatingKeyword.java
  src/main/generated/com/gamegoo/domain/notification/QNotification.java
  src/main/generated/com/gamegoo/domain/notification/QNotificationType.java
  src/main/generated/com/gamegoo/domain/report/QReport.java
  src/main/generated/com/gamegoo/domain/report/QReportType.java
  src/main/generated/com/gamegoo/domain/report/QReportTypeMapping.java
  src/main/java/com/gamegoo/config/JpaConfig.java
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chatroom.java
  src/main/java/com/gamegoo/domain/enums/ChatroomType.java
  src/main/java/com/gamegoo/dto/chat/ChatRequest.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/ChatRepository.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepository.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature

#91 [Feat/90] 채팅방 입장 API 구현
  src/main/generated/com/gamegoo/domain/chat/QChat.java
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chat.java
  src/main/java/com/gamegoo/domain/chat/MemberChatroom.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/repository/chat/ChatroomRepository.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature

#84 [Feat/68] 게시판 글 조회 관련 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature, :bug: bug

#88 [Feat/87] 로그아웃 API 개발
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/service/member/AuthService.java
Labels: :sparkles: feature

#93 [Feat/92] 채팅 메시지 등록 API 구현
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chat.java
  src/main/java/com/gamegoo/dto/chat/ChatRequest.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/util/TimestampUtil.java
Labels: :sparkles: feature

#95 [Feat/94] 채팅 메시지 내역 조회 API 구현
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature

#97 [Feat/96] 채팅 메시지 읽음 처리 API 구현
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/repository/chat/ChatRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
Labels: :sparkles: feature

#100 [Feat/99] 채팅방 시작, 나가기 기능 구현 및 리팩토링
  src/main/generated/com/gamegoo/domain/chat/QChatroom.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chatroom.java
  src/main/java/com/gamegoo/domain/chat/MemberChatroom.java
  src/main/java/com/gamegoo/dto/chat/ChatRequest.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/repository/chat/ChatroomRepository.java
  src/main/java/com/gamegoo/repository/chat/ChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/repository/chat/MemberChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature, :recycle: refactor
