Repository Gamegoo-repo/Gamegoo-server, pull requests merged in 2024-08, with the labels that each got.

#103 [Feat/83] 매칭 정보 DB 기록하는 API개발
  .github/workflows/gradle.yml
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/MatchingHandler.java
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/domain/MatchingRecord.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/dto/matching/MatchingResponse.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/repository/matching/MatchingRecordRepository.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature

#105 [Fix/104] application.yml 속성 추가
  src/main/resources/application.yml
Labels: :bug: bug

#107 [Fix/104] 채팅 전송 시각을 KST String으로 리턴하도록 변경
  .github/workflows/gradle.yml
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
  src/main/java/com/gamegoo/util/DatetimeUtil.java
Labels: :recycle: refactor, :bug: bug

#108 [Fix/104] DatetimeUtil에 ZonedDateTime 명시
  src/main/java/com/gamegoo/util/DatetimeUtil.java
Labels: :bug: bug

#109 [Fix/104] Dockerfile에 JVM 시간대 옵션 추가
  Dockerfile
Labels: :bug: bug

#106 [Fix/98] 회원가입 로직 수정
  src/main/generated/com/gamegoo/domain/QMatchingRecord.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/controller/member/RiotController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/domain/champion/MemberChampion.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/PasswordService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/service/member/RiotService.java
  src/main/java/com/gamegoo/util/CodeGeneratorUtil.java
  src/main/java/com/gamegoo/util/JWTUtil.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :recycle: refactor, :bug: bug

#112 [Fix/111] riotAPIKey 에러 해결
  .github/workflows/gradle.yml
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/resources/application.yml
Labels: :bug: bug

#101 [Feat/85] 매너 평가 등록 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/MannerHandler.java
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/domain/manner/MannerKeyword.java
  src/main/java/com/gamegoo/domain/manner/MannerRating.java
  src/main/java/com/gamegoo/domain/manner/MannerRatingKeyword.java
  src/main/java/com/gamegoo/dto/manner/MannerRequest.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/repository/manner/MannerKeywordRepository.java
  src/main/java/com/gamegoo/repository/manner/MannerRatingKeywordRepository.java
  src/main/java/com/gamegoo/repository/manner/MannerRatingRepository.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature

#114 [Fix/113] 게시판 글 작성 / 글 수정 페이지 프로필 이미지 수정 기능 추가
  src/main/generated/com/gamegoo/domain/board/QBoard.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#119 [Feat/110] 친구 요청 등록 API 구현
  src/main/generated/com/gamegoo/domain/friend/QFriend.java
  src/main/generated/com/gamegoo/domain/friend/QFriendRequests.java
  src/main/generated/com/gamegoo/domain/manner/QMannerRating.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/FriendHandler.java
  src/main/java/com/gamegoo/controller/member/BlockController.java
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/domain/friend/Friend.java
  src/main/java/com/gamegoo/domain/friend/FriendRequestStatus.java
  src/main/java/com/gamegoo/domain/friend/FriendRequests.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/repository/friend/FriendRepository.java
  src/main/java/com/gamegoo/repository/friend/FriendRequestsRepository.java
  src/main/java/com/gamegoo/service/member/BlockService.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/util/MemberUtils.java
Labels: :sparkles: feature, :recycle: refactor

#120 [Feat/115] 게시판 글 목록 조회 필터 기능 구현
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature

#122 [Fix/111] 회원 프로필 수정
  src/main/generated/com/gamegoo/domain/QMember.java
  src/main/generated/com/gamegoo/domain/board/QBoard.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/domain/Member.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/domain/champion/MemberChampion.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/PasswordService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :recycle: refactor, :bug: bug

#123 [Feat/116] JWT 토큰 없이 비밀번호 재설정하는 API 만들기
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/PasswordController.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/service/member/PasswordService.java
Labels: :sparkles: feature, :bug: bug

#125 [Feat/124] 알림 등록 메소드 구현 및 친구 요청 전송 시 알림 등록
  src/main/generated/com/gamegoo/domain/notification/QNotification.java
  src/main/generated/com/gamegoo/domain/notification/QNotificationType.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/NotificationHandler.java
  src/main/java/com/gamegoo/controller/TestController.java
  src/main/java/com/gamegoo/domain/notification/Notification.java
  src/main/java/com/gamegoo/domain/notification/NotificationType.java
  src/main/java/com/gamegoo/domain/notification/NotificationTypeTitle.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepository.java
  src/main/java/com/gamegoo/repository/notification/NotificationTypeRepository.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/service/notification/NotificationService.java
Labels: :sparkles: feature, :recycle: refactor

#130 [Feat/115] voice -> mike 컬럼 변경
  src/main/generated/com/gamegoo/domain/board/QBoard.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/domain/board/Board.java
  src/main/java/com/gamegoo/dto/board/BoardRequest.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor

#127 [Refactor/126] 회원 차단 관련 로직 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/domain/friend/FriendRequests.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/friend/FriendRepository.java
  src/main/java/com/gamegoo/repository/friend/FriendRequestsRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
  src/main/java/com/gamegoo/service/member/BlockService.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/util/MemberUtils.java
Labels: :sparkles: feature, :recycle: refactor

#131 [Fix/121] 게임 스타일 오류 수정
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :bug: bug

#129 [Feat/102] 매너 평가 수정 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/domain/manner/MannerRating.java
  src/main/java/com/gamegoo/domain/manner/MannerRatingKeyword.java
  src/main/java/com/gamegoo/dto/manner/MannerRequest.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature

#133 [Feat/128] 친구 관련 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/domain/friend/Friend.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/FriendService.java
Labels: :sparkles: feature, :recycle: refactor

#136 [Refactor/134] 채팅 관련 API endpoint 및 응답 값 수정
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/friend/FriendRepository.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/member/FriendService.java
Labels: :recycle: refactor

#143 [Feat/142] SocketService 메소드 구현 및 채팅 등록 API 로직 추가
  .github/workflows/gradle.yml
  src/main/generated/com/gamegoo/domain/QMatchingRecord.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/apiPayload/exception/handler/SocketHandler.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/socket/SocketService.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#146 [Fix/118] RIOT API 수정
  .gitignore
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/AuthController.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/domain/matching/MatchingRecord.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/dto/member/MemberRequest.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/filter/LoginFilter.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature, :bug: bug

#140 [Feat/139] 매너평가 조회 API 구현
  src/main/generated/com/gamegoo/domain/matching/QMatchingRecord.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature

#141 [Feat/138] 회원 API 관련 기능 추가 개발
  src/main/generated/com/gamegoo/domain/matching/QMatchingRecord.java
  src/main/generated/com/gamegoo/domain/member/QMember.java
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/member/AuthService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :bug: bug

#144 [Feat/132] 게시판 관련 추가 구현
  src/main/generated/com/gamegoo/domain/member/QMember.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/util/RiotUtil.java
Labels: :sparkles: feature

#148 [Refactor/147] 게시판, 매너평가 관련 코드 리팩토링
  src/main/generated/com/gamegoo/domain/matching/QMatchingRecord.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/repository/board/BoardRepository.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor

#152 [Feat/151] 게시판 관련 추가 구현 및 수정
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature, :bug: bug

#150 [Feat/145] 알림 관련 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/notification/NotificationController.java
  src/main/java/com/gamegoo/converter/NotificationConverter.java
  src/main/java/com/gamegoo/domain/notification/Notification.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/dto/notification/NotificationResponse.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepository.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepositoryCustom.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/service/notification/NotificationService.java
  src/main/java/com/gamegoo/service/socket/SocketService.java
Labels: :sparkles: feature, :recycle: refactor

#154 [Feat/149] 내가 받은 매너 평가 조회 API 구현
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/domain/member/Member.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/repository/manner/MannerRatingRepository.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature, :recycle: refactor

#157 [Feat/155] 매너 평가 조회 추가 구현
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature, :recycle: refactor

#156 [Feat/153] 채팅 시스템 메시지 기능 구현
  src/main/generated/com/gamegoo/domain/chat/QChat.java
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/domain/chat/Chat.java
  src/main/java/com/gamegoo/dto/chat/ChatRequest.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/repository/chat/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :sparkles: feature, :recycle: refactor

#159 [Feat/158] 게시판 글 작성 및 수정 시 포지션 선택에 전체 포지션 추가
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :sparkles: feature

#162 [Feat/160] 매너평가 관련 추가 구현
  src/main/java/com/gamegoo/controller/mannner/MannerController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/dto/manner/MannerResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature, :recycle: refactor

#164 [Refactor/161] 알림 목록 조회, 친구 목록 조회 API 수정
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/controller/notification/NotificationController.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepositoryCustom.java
  src/main/java/com/gamegoo/repository/notification/NotificationRepositoryCustomImpl.java
  src/main/java/com/gamegoo/service/member/BlockService.java
  src/main/java/com/gamegoo/service/member/FriendService.java
  src/main/java/com/gamegoo/service/notification/NotificationService.java
  src/main/java/com/gamegoo/util/SortUtil.java
Labels: :recycle: refactor

#166 [Feat/165] 매너평가 등록 시 알림 전송 기능 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/domain/notification/NotificationTypeTitle.java
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :sparkles: feature, :bug: bug

#168 [Feat/167] 친구 요청 취소 API 구현
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/member/FriendController.java
  src/main/java/com/gamegoo/service/member/FriendService.java
Labels: :sparkles: feature

#170 [Feat/169] 안읽은 채팅방 uuid 목록 조회 및 리팩토링
  src/main/java/com/gamegoo/controller/chat/ChatController.java
  src/main/java/com/gamegoo/converter/ChatConverter.java
  src/main/java/com/gamegoo/service/board/BoardService.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
  src/main/java/com/gamegoo/util/MemberUtils.java
Labels: :sparkles: feature, :recycle: refactor

#172 [Refactor/171] SpringbootTest 설정 및 기본 테스트코드 작성
  .github/workflows/pr-test.yml
  build.gradle
  src/test/java/com/gamegoo/chat/ChatServiceTest.java
  src/test/java/com/gamegoo/member/ProfileServiceTest.java
  src/test/resources/application.yml
Labels: ✅ test

#174 [Feat/163] 우선순위 계산 로직 API 개발
  src/main/java/com/gamegoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/domain/matching/MatchingStatus.java
  src/main/java/com/gamegoo/dto/matching/MatchingRequest.java
  src/main/java/com/gamegoo/dto/matching/MatchingResponse.java
  src/main/java/com/gamegoo/dto/matching/MemberPriority.java
  src/main/java/com/gamegoo/repository/matching/MatchingRecordRepository.java
  src/main/java/com/gamegoo/repository/member/MemberRepository.java
  src/main/java/com/gamegoo/scripts/MatchingRecordInitializer.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature

#177 [Feat/163] matching Status에 pending, found 추가
  src/main/java/com/gamegoo/domain/matching/MatchingStatus.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature

#180 [Refactor/179] 매칭 상태 변경 API 수정 및 추가 구현
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature, :recycle: refactor

#184 [Refactor/183] API 응답에 친구 요청 상태 및 차단 여부 추가
  src/main/java/com/gamegoo/config/SecurityConfig.java
  src/main/java/com/gamegoo/controller/member/ProfileController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/dto/member/MemberResponse.java
  src/main/java/com/gamegoo/service/chat/ChatCommandService.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :recycle: refactor, :bug: bug

#185 [Refactor/183] 채팅방 목록 조회 API 응답에 targetMemberId 추가
  src/main/java/com/gamegoo/dto/chat/ChatResponse.java
  src/main/java/com/gamegoo/service/chat/ChatQueryService.java
Labels: :recycle: refactor

#186 [Feat/181] 매칭 found API 구현 및 우선순위 계산 API 응답값 수정
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/dto/matching/MatchingResponse.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
  src/main/java/com/gamegoo/service/member/ProfileService.java
Labels: :sparkles: feature, :recycle: refactor

#191 [Fix/190] 비매너 평가 등록 관련 잘못된 예외처리(오류메시지) 수정
  src/main/java/com/gamegoo/service/manner/MannerService.java
Labels: :bug: bug

#188 [Feat/187] 매칭 성공 API 구현
  src/main/java/com/gamegoo/controller/matching/MatchingController.java
  src/main/java/com/gamegoo/converter/MemberConverter.java
  src/main/java/com/gamegoo/service/matching/MatchingService.java
Labels: :sparkles: feature

#189 [Refactor/182] 게시판 관련 API 응답 값 수정 및 페이징 단위 수정
  src/main/java/com/gamegoo/controller/board/BoardController.java
  src/main/java/com/gamegoo/dto/board/BoardResponse.java
  src/main/java/com/gamegoo/service/board/BoardService.java
Labels: :recycle: refactor
